baseURL = 'https://tomatofromsky.github.io/'
languageCode = 'ko-kr'
title = 'by tomatofromsky'
theme = "hugo-book"


# Book configuration
disablePathToLower = true
enableGitInfo = true

# Needed for mermaid/katex shortcodes
[markup]
[markup.goldmark.renderer]
unsafe = true

[markup.tableOfContents]
startLevel = 1


[caches.images]
dir = ':cacheDir/images'
